name: 'weather_data'
version: '1.0.0'
config-version: 2

profile: 'default'

# Chemins des différents types de fichiers
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

# Configuration des modèles
models:
  weather_data:
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging', 'weather']
    
    intermediate:
      +materialized: ephemeral
      +schema: staging
      +tags: ['intermediate', 'weather']
    
    marts:
      core:
        +materialized: table
        +schema: marts
        +tags: ['marts', 'core']
      
      reporting:
        +materialized: incremental
        +schema: marts
        +tags: ['marts', 'reporting']
        +on_schema_change: "sync_all_columns"