version: 2

sources:
  - name: raw
    database: DBT_DB
    schema: RAW
    tables:
      - name: weather_alerts
        description: "Données brutes des alertes météo de l'API NWS"
        data_tests:
          - dbt_utils.expression_is_true:
              expression: "SENT <= EFFECTIVE"
        columns:
          - name: ID
            data_tests:
              - unique
              - not_null
          - name: SENT
            description: "Temps d'envoi de l'alerte"
          - name: EFFECTIVE
            description: "Temps effectif de l'alerte"